import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { ChartAreaInteractive } from "@/components/chart";
import { ThemesProvider } from "@/themes/providers/theme-provider";
import { ThemeColorSelector, ThemeModeToggle } from "@/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ThemesProvider>
            <Suspense>
              <nav className="top-0 z-10 sticky flex justify-end items-center gap-2 bg-muted/30 backdrop-blur-sm px-10 py-4 w-full">
                <div className="flex flex-1 bg-primary p-2"></div>
                <Button>Button</Button>
                <Switch />
                <ThemeColorSelector />
                <ThemeModeToggle />
              </nav>
              <div className="flex bg-muted/20 p-6 border rounded-md w-full min-h-64">
                <ChartAreaInteractive />
              </div>
              {children}
            </Suspense>
          </ThemesProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
